import React,{useCallback,useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import{z}from"zod";
import"./style.css";

const totalsSchema=z.object({Requests:z.number(),Failed:z.number(),Total:z.number(),InputUncached:z.number(),CacheRead:z.number(),CacheCreation:z.number(),OutputNonReasoning:z.number(),Reasoning:z.number(),Unclassified:z.number(),LatencyP50MS:z.number(),LatencyP95MS:z.number(),TTFTP50MS:z.number(),TTFTP95MS:z.number(),CostNanoUSD:z.number(),CacheSavingsNanoUSD:z.number(),UnpricedEvents:z.number()});
const summarySchema=z.object({data:totalsSchema,dropped_events:z.number(),retention_days:z.number(),pricing:z.array(z.object({source:z.string(),version:z.string(),updated_at:z.string()}))});
const rowSchema=z.object({key:z.string(),Requests:z.number(),Failed:z.number(),Tokens:z.number(),CostNanoUSD:z.number()});
const breakdownSchema=z.object({data:z.array(rowSchema)});
const seriesSchema=z.object({data:z.array(z.object({Bucket:z.string(),Provider:z.string(),Requests:z.number(),Tokens:z.number(),CostNanoUSD:z.number()}))});
type Summary=z.infer<typeof summarySchema>;type Row=z.infer<typeof rowSchema>;type Series=z.infer<typeof seriesSchema>["data"];
type Period="24h"|"7d"|"30d"|"90d";type MetricName="cost"|"tokens";type Dimension="model"|"provider";

const copy={pt:{title:"Uso",subtitle:"Tokens, custos estimados e desempenho do gateway.",cost:"Custo",tokens:"Tokens",requests:"requisições",providers:"Providers",total:"Total",breakdown:"Detalhamento",model:"Modelo",provider:"Provider",share:"Participação",processed:"Processados",cached:"Entrada em cache",uncached:"Entrada sem cache",output:"Saída",reasoning:"Raciocínio",savings:"Economia de cache",success:"sucesso",latency:"latência p95",ttft:"TTFT p95",unpriced:"eventos sem preço",estimate:"Estimativa de API",source:"Fontes de preço",empty:"Sem uso neste período.",key:"Chave de management",connect:"Abrir dashboard",badKey:"Não foi possível autenticar com essa chave.",refresh:"Atualizar",allProviders:"Todos os providers"},en:{title:"Usage",subtitle:"Gateway tokens, estimated cost, and performance.",cost:"Cost",tokens:"Tokens",requests:"requests",providers:"Providers",total:"Total",breakdown:"Breakdown",model:"Model",provider:"Provider",share:"Share",processed:"Processed",cached:"Cached input",uncached:"Uncached input",output:"Output",reasoning:"Reasoning",savings:"Cache savings",success:"success",latency:"p95 latency",ttft:"p95 TTFT",unpriced:"unpriced events",estimate:"API estimate",source:"Pricing sources",empty:"No usage in this period.",key:"Management key",connect:"Open dashboard",badKey:"Could not authenticate with that key.",refresh:"Refresh",allProviders:"All providers"}}as const;
const colors:Record<string,string>={codex:"#5b5bd6",openrouter:"#8b5cf6",kimi:"#2185d0",xai:"#222222",anthropic:"#d97745",unknown:"#8b8b84"};
const compact=new Intl.NumberFormat(undefined,{notation:"compact",maximumFractionDigits:1});const integer=new Intl.NumberFormat();
function usd(nano:number){const value=nano/1e9;return new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",minimumFractionDigits:value<1?4:2,maximumFractionDigits:value<1?4:2}).format(value)}
function rowValue(row:Row,metric:MetricName){return metric==="cost"?row.CostNanoUSD:row.Tokens}function display(value:number,metric:MetricName){return metric==="cost"?usd(value):compact.format(value)}function color(provider:string){return colors[provider.toLowerCase()]??"#6c7a89"}
function startOf(period:Period){const hours:Record<Period,number>={"24h":24,"7d":168,"30d":720,"90d":2160};return new Date(Date.now()-hours[period]*36e5).toISOString()}

function App(){
 const[lang,setLang]=useState<"pt"|"en">(()=>navigator.language.toLowerCase().startsWith("pt")?"pt":"en");const t=copy[lang];
 const[key,setKey]=useState(()=>sessionStorage.getItem("usage-management-key")??"");const[draft,setDraft]=useState(key);
 const[period,setPeriod]=useState<Period>("30d");const[metric,setMetric]=useState<MetricName>("cost");const[dimension,setDimension]=useState<Dimension>("model");const[provider,setProvider]=useState("");
 const[summary,setSummary]=useState<Summary|null>(null);const[providers,setProviders]=useState<Row[]>([]);const[rows,setRows]=useState<Row[]>([]);const[series,setSeries]=useState<Series>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[refresh,setRefresh]=useState(0);
 const range=useMemo(()=>({from:startOf(period),to:new Date().toISOString()}),[period,refresh]);
 const api=useCallback(async(path:string,filtered=true)=>{const query=new URLSearchParams({from:range.from,to:range.to});if(filtered&&provider)query.set("provider",provider);const response=await fetch(`/v0/management/plugins/usage-analytics/${path}${path.includes("?")?"&":"?"}${query}`,{headers:{Authorization:`Bearer ${key}`},cache:"no-store"});if(!response.ok)throw new Error(String(response.status));return response.json()as Promise<unknown>},[key,provider,range]);
 useEffect(()=>{if(!key)return;let current=true;setLoading(true);setError("");const bucket=period==="24h"?"hour":"day";Promise.all([api("summary"),api("breakdown?dimension=provider",false),api(`breakdown?dimension=${dimension}`),api(`series?bucket=${bucket}&timezone_offset=${new Date().getTimezoneOffset()}`)]).then(([a,b,c,d])=>{if(current){setSummary(summarySchema.parse(a));setProviders(breakdownSchema.parse(b).data);setRows(breakdownSchema.parse(c).data);setSeries(seriesSchema.parse(d).data)}}).catch(()=>current&&setError(t.badKey)).finally(()=>current&&setLoading(false));return()=>{current=false}},[api,dimension,key,period,t.badKey]);
 function connect(){const clean=draft.trim();sessionStorage.setItem("usage-management-key",clean);setKey(clean)}
 if(!key)return <Login title={t.title}subtitle={t.subtitle}label={t.key}action={t.connect}value={draft}onChange={setDraft}onSubmit={connect}/>;
 const data=summary?.data;const success=data?.Requests?100-data.Failed/data.Requests*100:0;const providerTotal=providers.reduce((sum,row)=>sum+rowValue(row,metric),0);const cacheBase=(data?.InputUncached??0)+(data?.CacheRead??0)+(data?.CacheCreation??0);const cacheRate=cacheBase?(data?.CacheRead??0)/cacheBase*100:0;
 return <main className="app-shell"><header className="page-header"><div><div className="crumb">CLIProxyAPI <span>/</span> {t.title}</div><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="header-actions"><select aria-label="Language"value={lang}onChange={event=>setLang(event.target.value as"pt"|"en")}><option value="pt">PT-BR</option><option value="en">EN</option></select><button className="icon-button"title={t.refresh}onClick={()=>setRefresh(value=>value+1)}>↻</button></div></header>
 <nav className="toolbar"><Segmented value={metric}items={[{value:"cost",label:t.cost},{value:"tokens",label:t.tokens}]}onChange={value=>setMetric(value as MetricName)}/><div className="segmented periods">{(["24h","7d","30d","90d"]as Period[]).map(item=><button key={item}className={period===item?"active":""}onClick={()=>setPeriod(item)}>{item}</button>)}</div><select className="provider-filter"value={provider}onChange={event=>setProvider(event.target.value)}><option value="">{t.allProviders}</option>{providers.map(row=><option key={row.key}value={row.key}>{row.key}</option>)}</select></nav>
 {loading&&<div className="progress"/>}{error&&<div className="notice error">{error}</div>}{data&&<><section className="overview"><div className="ledger"><div className="section-kicker">{t.estimate}</div><div className="hero-value">{metric==="cost"?usd(data.CostNanoUSD):compact.format(data.Total)}</div><div className="hero-meta"><span>{integer.format(data.Requests)} {t.requests}</span><i/><span>{success.toFixed(1)}% {t.success}</span></div><div className="provider-ledger">{providers.slice(0,6).map(row=>{const value=rowValue(row,metric);const share=providerTotal?value/providerTotal*100:0;return <button key={row.key}className="provider-row"onClick={()=>setProvider(current=>current===row.key?"":row.key)}><span className="provider-mark"style={{background:color(row.key)}}/><span className="provider-name">{row.key||"unknown"}</span><span className="provider-share">{share.toFixed(1)}%</span><strong>{display(value,metric)}</strong></button>})}</div></div><div className="chart-panel"><div className="chart-heading"><div><span>{period==="24h"?"HOURLY":"DAILY"}</span><strong>{t.providers}</strong></div><div className="legend">{providers.slice(0,4).map(row=><span key={row.key}><i style={{background:color(row.key)}}/>{row.key}</span>)}</div></div><UsageChart data={series}metric={metric}empty={t.empty}/></div></section>
 <section className="totals"><Metric label={t.processed}value={data.Total}/><Metric label={t.cached}value={data.CacheRead}detail={`${cacheRate.toFixed(1)}% cache hit`}/><Metric label={t.uncached}value={data.InputUncached}/><Metric label={t.output}value={data.OutputNonReasoning}/><Metric label={t.reasoning}value={data.Reasoning}/><Metric label={t.savings}value={data.CacheSavingsNanoUSD}money/></section>
 <section className="details"><div className="details-head"><div><div className="section-kicker">{t.breakdown}</div><h2>{dimension==="model"?t.model:t.provider}</h2></div><Segmented value={dimension}items={[{value:"model",label:t.model},{value:"provider",label:t.provider}]}onChange={value=>setDimension(value as Dimension)}/></div>{rows.length?<div className="table-wrap"><table><thead><tr><th>{dimension==="model"?t.model:t.provider}</th><th>{t.requests}</th><th>{t.tokens}</th><th>{t.cost}</th><th>{t.share}</th></tr></thead><tbody>{rows.map(row=>{const total=metric==="cost"?data.CostNanoUSD:data.Total;const share=total?rowValue(row,metric)/total*100:0;return <tr key={row.key}><td><span className="model-dot"style={{background:dimension==="provider"?color(row.key):undefined}}/>{row.key||"unknown"}</td><td>{integer.format(row.Requests)}</td><td>{compact.format(row.Tokens)}</td><td>{row.CostNanoUSD?usd(row.CostNanoUSD):"—"}</td><td><div className="share-cell"><span>{share.toFixed(1)}%</span><i><b style={{width:`${Math.min(100,share)}%`}}/></i></div></td></tr>})}</tbody></table></div>:<div className="empty">{t.empty}</div>}</section>
 <footer className="pricing-note"><div><strong>{t.source}</strong><span>{summary.pricing.filter(item=>item.source).map(item=>item.source).join(" + ")||"—"}</span></div><div><strong>{t.estimate}</strong><span>{data.UnpricedEvents} {t.unpriced} · {data.LatencyP95MS} ms {t.latency} · {data.TTFTP95MS} ms {t.ttft}</span></div></footer></>}</main>
}
function Segmented({value,items,onChange}:{value:string;items:{value:string;label:string}[];onChange:(value:string)=>void}){return <div className="segmented">{items.map(item=><button key={item.value}className={value===item.value?"active":""}onClick={()=>onChange(item.value)}>{item.label}</button>)}</div>}
function UsageChart({data,metric,empty}:{data:Series;metric:MetricName;empty:string}){const providers=[...new Set(data.map(row=>row.Provider))].slice(0,4);const buckets=[...new Set(data.map(row=>row.Bucket))];if(!data.length)return <div className="chart-empty">{empty}</div>;const max=Math.max(...data.map(row=>metric==="cost"?row.CostNanoUSD:row.Tokens),1);const width=720,height=250,pad=18;return <div className="chart"><svg viewBox={`0 0 ${width} ${height}`}role="img"><g className="grid">{[0,1,2,3,4].map(index=><line key={index}x1={pad}x2={width-pad}y1={pad+(height-pad*2)*index/4}y2={pad+(height-pad*2)*index/4}/>)}</g>{providers.map(provider=>{const points=buckets.map((bucket,index)=>{const row=data.find(item=>item.Bucket===bucket&&item.Provider===provider);const value=row?(metric==="cost"?row.CostNanoUSD:row.Tokens):0;const x=pad+(width-pad*2)*(buckets.length===1?.5:index/(buckets.length-1));const y=height-pad-(height-pad*2)*(value/max);return`${x},${y}`}).join(" ");return <polyline key={provider}points={points}fill="none"stroke={color(provider)}strokeWidth="2.5"strokeLinejoin="round"strokeLinecap="round"/>})}</svg><div className="chart-axis"><span>{buckets[0]?.slice(5).replace("T"," ")}</span><span>{buckets.at(-1)?.slice(5).replace("T"," ")}</span></div></div>}
function Metric({label,value,detail,money=false}:{label:string;value:number;detail?:string;money?:boolean}){return <div><span>{label}</span><strong>{money?usd(value):compact.format(value)}</strong>{detail&&<small>{detail}</small>}</div>}
function Login({title,subtitle,label,action,value,onChange,onSubmit}:{title:string;subtitle:string;label:string;action:string;value:string;onChange:(value:string)=>void;onSubmit:()=>void}){return <main className="login"><section><div className="login-mark">UA</div><div className="crumb">CLIProxyAPI / {title}</div><h1>{title}</h1><p>{subtitle}</p><label>{label}<input autoFocus type="password"autoComplete="off"value={value}onChange={event=>onChange(event.target.value)}onKeyDown={event=>event.key==="Enter"&&onSubmit()}/></label><button className="primary"onClick={onSubmit}>{action}</button></section></main>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
