import React, { useCallback, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { z } from "zod";
import "./style.css";

const summarySchema = z.object({ data: z.object({ Requests:z.number(), Failed:z.number(), Total:z.number(), InputUncached:z.number(), CacheRead:z.number(), CacheCreation:z.number(), OutputNonReasoning:z.number(), Reasoning:z.number(), Unclassified:z.number(), LatencyP50MS:z.number(), LatencyP95MS:z.number(), TTFTP50MS:z.number(), TTFTP95MS:z.number(), CostNanoUSD:z.number(), CacheSavingsNanoUSD:z.number(), UnpricedEvents:z.number() }), dropped_events:z.number() });
const breakdownSchema = z.object({ data:z.array(z.object({key:z.string(),Requests:z.number(),Failed:z.number(),Tokens:z.number(),CostNanoUSD:z.number()})) });
type Summary = z.infer<typeof summarySchema>["data"];
type Breakdown = z.infer<typeof breakdownSchema>["data"];
type Period = "24h"|"7d"|"30d"|"90d";
const labels={pt:{title:"Uso e métricas",subtitle:"Uma visão independente de provider sobre tokens, cache, custo e confiabilidade.",key:"Chave de management",connect:"Conectar",requests:"Requisições",tokens:"Tokens",success:"Sucesso",latency:"Latência p95",cache:"Cache hit",input:"Entrada sem cache",read:"Cache lido",write:"Cache criado",output:"Saída",reasoning:"Reasoning",unknown:"Não classificados",providers:"Uso por provider",empty:"Ainda não há dados neste período.",cost:"Custo",tokenMode:"Tokens",unpriced:"eventos sem preço",badKey:"Não foi possível autenticar. Confira a chave de management."},en:{title:"Usage & metrics",subtitle:"A provider-independent view of tokens, cache, cost and reliability.",key:"Management key",connect:"Connect",requests:"Requests",tokens:"Tokens",success:"Success",latency:"p95 latency",cache:"Cache hit",input:"Uncached input",read:"Cache read",write:"Cache created",output:"Output",reasoning:"Reasoning",unknown:"Unclassified",providers:"Usage by provider",empty:"There is no data in this period yet.",cost:"Cost",tokenMode:"Tokens",unpriced:"unpriced events",badKey:"Authentication failed. Check the management key."}} as const;

function formatNumber(value:number){return new Intl.NumberFormat().format(value)}
function usd(nano:number){return new Intl.NumberFormat(undefined,{style:"currency",currency:"USD",maximumFractionDigits:4}).format(nano/1e9)}
function App(){
 const [lang,setLang]=useState<"pt"|"en">(()=>navigator.language.toLowerCase().startsWith("pt")?"pt":"en");const t=labels[lang];
 const [key,setKey]=useState(()=>sessionStorage.getItem("usage-management-key")??"");const [draft,setDraft]=useState(key);const[period,setPeriod]=useState<Period>("24h");const[mode,setMode]=useState<"tokens"|"cost">("tokens");const[summary,setSummary]=useState<Summary|null>(null);const[breakdown,setBreakdown]=useState<Breakdown>([]);const[error,setError]=useState("");const[loading,setLoading]=useState(false);
 const from=useMemo(()=>{const hours={"24h":24,"7d":168,"30d":720,"90d":2160}[period];return new Date(Date.now()-hours*3600e3).toISOString()},[period]);
 const api=useCallback(async(path:string)=>{const separator=path.includes("?")?"&":"?";const response=await fetch(`/v0/management/plugins/usage-analytics/${path}${separator}from=${encodeURIComponent(from)}&to=${encodeURIComponent(new Date().toISOString())}`,{headers:{Authorization:`Bearer ${key}`},cache:"no-store"});if(!response.ok)throw new Error(String(response.status));return response.json() as Promise<unknown>},[from,key]);
 useEffect(()=>{if(!key)return;let active=true;setLoading(true);setError("");Promise.all([api("summary"),api("breakdown?dimension=provider")]).then(([s,b])=>{if(active){setSummary(summarySchema.parse(s).data);setBreakdown(breakdownSchema.parse(b).data)}}).catch(()=>active&&setError(t.badKey)).finally(()=>active&&setLoading(false));return()=>{active=false}},[api,key,t.badKey]);
 const connect=()=>{sessionStorage.setItem("usage-management-key",draft);setKey(draft)};
 if(!key)return <main className="login"><section><div className="mark">UA</div><h1>{t.title}</h1><p>{t.subtitle}</p><label>{t.key}<input type="password" autoComplete="off" value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>e.key==="Enter"&&connect()}/></label><button onClick={connect}>{t.connect}</button></section></main>;
 const success=summary&&summary.Requests?100-(summary.Failed/summary.Requests*100):0;const cacheBase=(summary?.InputUncached??0)+(summary?.CacheRead??0)+(summary?.CacheCreation??0);const cacheRate=cacheBase?((summary?.CacheRead??0)/cacheBase*100):0;const max=Math.max(...breakdown.map(x=>mode==="tokens"?x.Tokens:x.CostNanoUSD),1);
 return <main><header><div><div className="eyebrow">CLIPROXYAPI</div><h1>{t.title}</h1><p>{t.subtitle}</p></div><div className="controls"><select value={lang} onChange={e=>setLang(e.target.value as "pt"|"en")}><option value="pt">PT-BR</option><option value="en">EN</option></select><div className="segmented">{(["24h","7d","30d","90d"] as Period[]).map(p=><button className={period===p?"active":""} onClick={()=>setPeriod(p)} key={p}>{p}</button>)}</div></div></header>
 {error&&<div className="error">{error}</div>}{loading&&<div className="loader"/>}{summary&&<><section className="cards"><Card label={t.requests} value={formatNumber(summary.Requests)}/><Card label={t.tokens} value={formatNumber(summary.Total)}/><Card label={t.success} value={`${success.toFixed(1)}%`}/><Card label={t.latency} value={`${formatNumber(summary.LatencyP95MS)} ms`}/><Card label={t.cache} value={`${cacheRate.toFixed(1)}%`}/></section><section className="panel token-panel"><div className="panel-title"><div><span>ACCOUNTING</span><h2>{t.tokens}</h2></div><div className="segmented"><button className={mode==="tokens"?"active":""} onClick={()=>setMode("tokens")}>{t.tokenMode}</button><button className={mode==="cost"?"active":""} onClick={()=>setMode("cost")}>{t.cost}</button></div></div><div className="token-grid"><Metric label={t.input} value={summary.InputUncached} color="#7394ff"/><Metric label={t.read} value={summary.CacheRead} color="#2ed3a2"/><Metric label={t.write} value={summary.CacheCreation} color="#d6a85b"/><Metric label={t.output} value={summary.OutputNonReasoning} color="#c37cff"/><Metric label={t.reasoning} value={summary.Reasoning} color="#ff718b"/><Metric label={t.unknown} value={summary.Unclassified} color="#737887"/></div>{mode==="cost"&&<p className="muted">{usd(summary.CostNanoUSD)} · {summary.UnpricedEvents} {t.unpriced}</p>}</section><section className="panel"><div className="panel-title"><div><span>BREAKDOWN</span><h2>{t.providers}</h2></div></div>{breakdown.length===0?<p className="empty">{t.empty}</p>:<div className="bars">{breakdown.map(row=>{const value=mode==="tokens"?row.Tokens:row.CostNanoUSD;return <div className="bar-row" key={row.key}><div><strong>{row.key||"unknown"}</strong><small>{formatNumber(row.Requests)} {t.requests.toLowerCase()}</small></div><div className="track"><i style={{width:`${Math.max(2,value/max*100)}%`}}/></div><b>{mode==="tokens"?formatNumber(value):usd(value)}</b></div>})}</div>}</section></>}
 </main>
}
function Card({label,value}:{label:string;value:string}){return <article className="card"><span>{label}</span><strong>{value}</strong></article>}
function Metric({label,value,color}:{label:string;value:number;color:string}){return <div className="metric"><i style={{background:color}}/><span>{label}</span><strong>{formatNumber(value)}</strong></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
